# KengaOS — конфигурация Limine bootloader
timeout: 5
default_entry: 1
serial: yes
verbosity: verbose

resolution: 1024x768x32

/KengaOS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/initrd.tar
    cmdline: KENGAOS_LANG=ru
